DROP DATABASE IF EXISTS INFO_MAIS;
CREATE DATABASE INFO_MAIS;
USE INFO_MAIS;


 DROP TABLE IF EXISTS INTERESSE;
CREATE TABLE INTERESSE (ID_OPCAO INT PRIMARY KEY NOT NULL AUTO_INCREMENT ,
 NOME_OPCAO VARCHAR (200) NOT NULL,
 VALOR_FORMULARIO VARCHAR(50) NOT NULL );
 
CREATE TABLE
 USUARIO (ID_USUARIO INT PRIMARY KEY NOT NULL AUTO_INCREMENT ,
 NOME VARCHAR (200) NOT NULL,
 EMAIL VARCHAR (200) UNIQUE NOT NULL,
 DATA_NASCIMENTO DATE NOT NULL,
 SENHA_HASH  VARCHAR(250) NOT NULL );
 
 
 CREATE TABLE USUARIO_INTERESSE (ID_USUARIO INT NOT NULL,
ID_OPCAO INT NOT NULL ,

PRIMARY KEY (ID_USUARIO,ID_OPCAO),

foreign key (ID_USUARIO) REFERENCES USUARIO (ID_USUARIO),
FOREIGN KEY (ID_OPCAO)  REFERENCES INTERESSE (ID_OPCAO)  );


INSERT INTO INTERESSE (NOME_OPCAO, VALOR_FORMULARIO) VALUES
('Tecnologia', 'tecnologia'),
('Cultura', 'cultura'),
('Esportes', 'esportes'),
('Viagens', 'viagens'),
('Entretenimento', 'entretenimento'),
('Ciência', 'ciencia'),
('Saúde', 'saude'),
('Política', 'politica'),
('Negócios e Finanças', 'negocios'),
('Lifestyle', 'lifestyle'),
('História', 'historia'),
('Sociedade', 'sociedade');

SELECT * FROM INTERESSE;
